services:
  db:
    image: postgres:15-alpine
    container_name: newsnack-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: newsnack
      POSTGRES_USER: leekim
      POSTGRES_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
